// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"habitscape/backend/ent/admin"
	"habitscape/backend/ent/habit"
	"habitscape/backend/ent/user"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// Admin is the model entity for the Admin schema.
type Admin struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AdminQuery when eager-loading is set.
	Edges        AdminEdges `json:"edges"`
	habit_admins *int
	user_admins  *int
}

// AdminEdges holds the relations/edges for other nodes in the graph.
type AdminEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Habit holds the value of the habit edge.
	Habit *Habit `json:"habit,omitempty"`
	// Invitations holds the value of the invitations edge.
	Invitations []*Invitation `json:"invitations,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AdminEdges) UserOrErr() (*User, error) {
	if e.loadedTypes[0] {
		if e.User == nil {
			// The edge user was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.User, nil
	}
	return nil, &NotLoadedError{edge: "user"}
}

// HabitOrErr returns the Habit value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AdminEdges) HabitOrErr() (*Habit, error) {
	if e.loadedTypes[1] {
		if e.Habit == nil {
			// The edge habit was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: habit.Label}
		}
		return e.Habit, nil
	}
	return nil, &NotLoadedError{edge: "habit"}
}

// InvitationsOrErr returns the Invitations value or an error if the edge
// was not loaded in eager-loading.
func (e AdminEdges) InvitationsOrErr() ([]*Invitation, error) {
	if e.loadedTypes[2] {
		return e.Invitations, nil
	}
	return nil, &NotLoadedError{edge: "invitations"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Admin) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case admin.FieldID:
			values[i] = new(sql.NullInt64)
		case admin.ForeignKeys[0]: // habit_admins
			values[i] = new(sql.NullInt64)
		case admin.ForeignKeys[1]: // user_admins
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Admin", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Admin fields.
func (a *Admin) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case admin.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			a.ID = int(value.Int64)
		case admin.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field habit_admins", value)
			} else if value.Valid {
				a.habit_admins = new(int)
				*a.habit_admins = int(value.Int64)
			}
		case admin.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_admins", value)
			} else if value.Valid {
				a.user_admins = new(int)
				*a.user_admins = int(value.Int64)
			}
		}
	}
	return nil
}

// QueryUser queries the "user" edge of the Admin entity.
func (a *Admin) QueryUser() *UserQuery {
	return (&AdminClient{config: a.config}).QueryUser(a)
}

// QueryHabit queries the "habit" edge of the Admin entity.
func (a *Admin) QueryHabit() *HabitQuery {
	return (&AdminClient{config: a.config}).QueryHabit(a)
}

// QueryInvitations queries the "invitations" edge of the Admin entity.
func (a *Admin) QueryInvitations() *InvitationQuery {
	return (&AdminClient{config: a.config}).QueryInvitations(a)
}

// Update returns a builder for updating this Admin.
// Note that you need to call Admin.Unwrap() before calling this method if this Admin
// was returned from a transaction, and the transaction was committed or rolled back.
func (a *Admin) Update() *AdminUpdateOne {
	return (&AdminClient{config: a.config}).UpdateOne(a)
}

// Unwrap unwraps the Admin entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (a *Admin) Unwrap() *Admin {
	tx, ok := a.config.driver.(*txDriver)
	if !ok {
		panic("ent: Admin is not a transactional entity")
	}
	a.config.driver = tx.drv
	return a
}

// String implements the fmt.Stringer.
func (a *Admin) String() string {
	var builder strings.Builder
	builder.WriteString("Admin(")
	builder.WriteString(fmt.Sprintf("id=%v", a.ID))
	builder.WriteByte(')')
	return builder.String()
}

// Admins is a parsable slice of Admin.
type Admins []*Admin

func (a Admins) config(cfg config) {
	for _i := range a {
		a[_i].config = cfg
	}
}
