// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"habitscape/backend/ent/completion"
	"habitscape/backend/ent/habit"
	"habitscape/backend/ent/predicate"
	"habitscape/backend/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CompletionUpdate is the builder for updating Completion entities.
type CompletionUpdate struct {
	config
	hooks    []Hook
	mutation *CompletionMutation
}

// Where appends a list predicates to the CompletionUpdate builder.
func (cu *CompletionUpdate) Where(ps ...predicate.Completion) *CompletionUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetText sets the "text" field.
func (cu *CompletionUpdate) SetText(s string) *CompletionUpdate {
	cu.mutation.SetText(s)
	return cu
}

// SetDateCompleted sets the "date_completed" field.
func (cu *CompletionUpdate) SetDateCompleted(t time.Time) *CompletionUpdate {
	cu.mutation.SetDateCompleted(t)
	return cu
}

// SetNillableDateCompleted sets the "date_completed" field if the given value is not nil.
func (cu *CompletionUpdate) SetNillableDateCompleted(t *time.Time) *CompletionUpdate {
	if t != nil {
		cu.SetDateCompleted(*t)
	}
	return cu
}

// SetStatus sets the "status" field.
func (cu *CompletionUpdate) SetStatus(c completion.Status) *CompletionUpdate {
	cu.mutation.SetStatus(c)
	return cu
}

// SetHabitID sets the "habit" edge to the Habit entity by ID.
func (cu *CompletionUpdate) SetHabitID(id int) *CompletionUpdate {
	cu.mutation.SetHabitID(id)
	return cu
}

// SetHabit sets the "habit" edge to the Habit entity.
func (cu *CompletionUpdate) SetHabit(h *Habit) *CompletionUpdate {
	return cu.SetHabitID(h.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (cu *CompletionUpdate) SetUserID(id int) *CompletionUpdate {
	cu.mutation.SetUserID(id)
	return cu
}

// SetUser sets the "user" edge to the User entity.
func (cu *CompletionUpdate) SetUser(u *User) *CompletionUpdate {
	return cu.SetUserID(u.ID)
}

// Mutation returns the CompletionMutation object of the builder.
func (cu *CompletionUpdate) Mutation() *CompletionMutation {
	return cu.mutation
}

// ClearHabit clears the "habit" edge to the Habit entity.
func (cu *CompletionUpdate) ClearHabit() *CompletionUpdate {
	cu.mutation.ClearHabit()
	return cu
}

// ClearUser clears the "user" edge to the User entity.
func (cu *CompletionUpdate) ClearUser() *CompletionUpdate {
	cu.mutation.ClearUser()
	return cu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *CompletionUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(cu.hooks) == 0 {
		if err = cu.check(); err != nil {
			return 0, err
		}
		affected, err = cu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CompletionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cu.check(); err != nil {
				return 0, err
			}
			cu.mutation = mutation
			affected, err = cu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cu.hooks) - 1; i >= 0; i-- {
			if cu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CompletionUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CompletionUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CompletionUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *CompletionUpdate) check() error {
	if v, ok := cu.mutation.Text(); ok {
		if err := completion.TextValidator(v); err != nil {
			return &ValidationError{Name: "text", err: fmt.Errorf(`ent: validator failed for field "Completion.text": %w`, err)}
		}
	}
	if v, ok := cu.mutation.Status(); ok {
		if err := completion.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Completion.status": %w`, err)}
		}
	}
	if _, ok := cu.mutation.HabitID(); cu.mutation.HabitCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Completion.habit"`)
	}
	if _, ok := cu.mutation.UserID(); cu.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Completion.user"`)
	}
	return nil
}

func (cu *CompletionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   completion.Table,
			Columns: completion.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: completion.FieldID,
			},
		},
	}
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.Text(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: completion.FieldText,
		})
	}
	if value, ok := cu.mutation.DateCompleted(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: completion.FieldDateCompleted,
		})
	}
	if value, ok := cu.mutation.Status(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: completion.FieldStatus,
		})
	}
	if cu.mutation.HabitCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   completion.HabitTable,
			Columns: []string{completion.HabitColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: habit.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.HabitIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   completion.HabitTable,
			Columns: []string{completion.HabitColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: habit.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   completion.UserTable,
			Columns: []string{completion.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   completion.UserTable,
			Columns: []string{completion.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{completion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// CompletionUpdateOne is the builder for updating a single Completion entity.
type CompletionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CompletionMutation
}

// SetText sets the "text" field.
func (cuo *CompletionUpdateOne) SetText(s string) *CompletionUpdateOne {
	cuo.mutation.SetText(s)
	return cuo
}

// SetDateCompleted sets the "date_completed" field.
func (cuo *CompletionUpdateOne) SetDateCompleted(t time.Time) *CompletionUpdateOne {
	cuo.mutation.SetDateCompleted(t)
	return cuo
}

// SetNillableDateCompleted sets the "date_completed" field if the given value is not nil.
func (cuo *CompletionUpdateOne) SetNillableDateCompleted(t *time.Time) *CompletionUpdateOne {
	if t != nil {
		cuo.SetDateCompleted(*t)
	}
	return cuo
}

// SetStatus sets the "status" field.
func (cuo *CompletionUpdateOne) SetStatus(c completion.Status) *CompletionUpdateOne {
	cuo.mutation.SetStatus(c)
	return cuo
}

// SetHabitID sets the "habit" edge to the Habit entity by ID.
func (cuo *CompletionUpdateOne) SetHabitID(id int) *CompletionUpdateOne {
	cuo.mutation.SetHabitID(id)
	return cuo
}

// SetHabit sets the "habit" edge to the Habit entity.
func (cuo *CompletionUpdateOne) SetHabit(h *Habit) *CompletionUpdateOne {
	return cuo.SetHabitID(h.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (cuo *CompletionUpdateOne) SetUserID(id int) *CompletionUpdateOne {
	cuo.mutation.SetUserID(id)
	return cuo
}

// SetUser sets the "user" edge to the User entity.
func (cuo *CompletionUpdateOne) SetUser(u *User) *CompletionUpdateOne {
	return cuo.SetUserID(u.ID)
}

// Mutation returns the CompletionMutation object of the builder.
func (cuo *CompletionUpdateOne) Mutation() *CompletionMutation {
	return cuo.mutation
}

// ClearHabit clears the "habit" edge to the Habit entity.
func (cuo *CompletionUpdateOne) ClearHabit() *CompletionUpdateOne {
	cuo.mutation.ClearHabit()
	return cuo
}

// ClearUser clears the "user" edge to the User entity.
func (cuo *CompletionUpdateOne) ClearUser() *CompletionUpdateOne {
	cuo.mutation.ClearUser()
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *CompletionUpdateOne) Select(field string, fields ...string) *CompletionUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Completion entity.
func (cuo *CompletionUpdateOne) Save(ctx context.Context) (*Completion, error) {
	var (
		err  error
		node *Completion
	)
	if len(cuo.hooks) == 0 {
		if err = cuo.check(); err != nil {
			return nil, err
		}
		node, err = cuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CompletionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cuo.check(); err != nil {
				return nil, err
			}
			cuo.mutation = mutation
			node, err = cuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(cuo.hooks) - 1; i >= 0; i-- {
			if cuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CompletionUpdateOne) SaveX(ctx context.Context) *Completion {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *CompletionUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CompletionUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *CompletionUpdateOne) check() error {
	if v, ok := cuo.mutation.Text(); ok {
		if err := completion.TextValidator(v); err != nil {
			return &ValidationError{Name: "text", err: fmt.Errorf(`ent: validator failed for field "Completion.text": %w`, err)}
		}
	}
	if v, ok := cuo.mutation.Status(); ok {
		if err := completion.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Completion.status": %w`, err)}
		}
	}
	if _, ok := cuo.mutation.HabitID(); cuo.mutation.HabitCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Completion.habit"`)
	}
	if _, ok := cuo.mutation.UserID(); cuo.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Completion.user"`)
	}
	return nil
}

func (cuo *CompletionUpdateOne) sqlSave(ctx context.Context) (_node *Completion, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   completion.Table,
			Columns: completion.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: completion.FieldID,
			},
		},
	}
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Completion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, completion.FieldID)
		for _, f := range fields {
			if !completion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != completion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.Text(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: completion.FieldText,
		})
	}
	if value, ok := cuo.mutation.DateCompleted(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: completion.FieldDateCompleted,
		})
	}
	if value, ok := cuo.mutation.Status(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: completion.FieldStatus,
		})
	}
	if cuo.mutation.HabitCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   completion.HabitTable,
			Columns: []string{completion.HabitColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: habit.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.HabitIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   completion.HabitTable,
			Columns: []string{completion.HabitColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: habit.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   completion.UserTable,
			Columns: []string{completion.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   completion.UserTable,
			Columns: []string{completion.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Completion{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{completion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
