// Code generated by entc, DO NOT EDIT.

package invitation

const (
	// Label holds the string label denoting the invitation type in the database.
	Label = "invitation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// EdgeHabit holds the string denoting the habit edge name in mutations.
	EdgeHabit = "habit"
	// EdgeAdmin holds the string denoting the admin edge name in mutations.
	EdgeAdmin = "admin"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the invitation in the database.
	Table = "invitations"
	// HabitTable is the table that holds the habit relation/edge.
	HabitTable = "invitations"
	// HabitInverseTable is the table name for the Habit entity.
	// It exists in this package in order to avoid circular dependency with the "habit" package.
	HabitInverseTable = "habits"
	// HabitColumn is the table column denoting the habit relation/edge.
	HabitColumn = "habit_invitations"
	// AdminTable is the table that holds the admin relation/edge.
	AdminTable = "invitations"
	// AdminInverseTable is the table name for the Admin entity.
	// It exists in this package in order to avoid circular dependency with the "admin" package.
	AdminInverseTable = "admins"
	// AdminColumn is the table column denoting the admin relation/edge.
	AdminColumn = "admin_invitations"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "invitations"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_invitations"
)

// Columns holds all SQL columns for invitation fields.
var Columns = []string{
	FieldID,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "invitations"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"admin_invitations",
	"habit_invitations",
	"user_invitations",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
